//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoTimeManager.WebUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDoTimeManager.WebUI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authentication.
        /// </summary>
        public static string authentication {
            get {
                return ResourceManager.GetString("authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build something worth shipping..
        /// </summary>
        public static string Build_something_worth_shipping_ {
            get {
                return ResourceManager.GetString("Build something worth shipping.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact your forge admin.
        /// </summary>
        public static string Contact_your_forge_admin {
            get {
                return ResourceManager.GetString("Contact your forge admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string Create_an_account {
            get {
                return ResourceManager.GetString("Create an account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or username.
        /// </summary>
        public static string Email_or_username {
            get {
                return ResourceManager.GetString("Email or username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge clarity.
        /// </summary>
        public static string Forge_clarity {
            get {
                return ResourceManager.GetString("Forge clarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free for solo smiths. No card required. Bring your team when you&apos;re ready..
        /// </summary>
        public static string Free_for_solo_smiths__No_card_required__Bring_your_team_when_you_re_ready_ {
            get {
                return ResourceManager.GetString("Free for solo smiths. No card required. Bring your team when you\'re ready.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from chaos..
        /// </summary>
        public static string from_chaos_ {
            get {
                return ResourceManager.GetString("from chaos.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me signed in.
        /// </summary>
        public static string Keep_me_signed_in {
            get {
                return ResourceManager.GetString("Keep me signed in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keeps your account safe..
        /// </summary>
        public static string keeps_your_account_safe_ {
            get {
                return ResourceManager.GetString("keeps your account safe.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to TaskForge?.
        /// </summary>
        public static string New_to_TaskForge_ {
            get {
                return ResourceManager.GetString("New to TaskForge?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string SIGN_IN {
            get {
                return ResourceManager.GetString("SIGN IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string sign_in_step_label {
            get {
                return ResourceManager.GetString("sign-in_step-label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP.
        /// </summary>
        public static string STEP {
            get {
                return ResourceManager.GetString("STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strike the anvil.
        /// </summary>
        public static string Strike_the_anvil {
            get {
                return ResourceManager.GetString("Strike the anvil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to takes 30s..
        /// </summary>
        public static string takes_30s_ {
            get {
                return ResourceManager.GetString("takes 30s.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time logs.
        /// </summary>
        public static string TimeLogs {
            get {
                return ResourceManager.GetString("TimeLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track, prioritize, and ship work with the precision of a master smith..
        /// </summary>
        public static string Track__prioritize__and_ship_work_with_the_precision_of_a_master_smith_ {
            get {
                return ResourceManager.GetString("Track, prioritize, and ship work with the precision of a master smith.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trouble signing in?.
        /// </summary>
        public static string Trouble_signing_in_ {
            get {
                return ResourceManager.GetString("Trouble signing in?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor auth.
        /// </summary>
        public static string two_fa_step_label {
            get {
                return ResourceManager.GetString("two-fa_step-label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor.
        /// </summary>
        public static string Two_factor {
            get {
                return ResourceManager.GetString("Two-factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We send a one-time code to your inbox every time you sign in. Even if someone learns your password, they can&apos;t reach your work without it..
        /// </summary>
        public static string We_send_a_one_time_code_to_your_inbox_every_time_you_sign_in__Even_if_someone_learns_your_password__they_can_t_reach_your_work_without_it_ {
            get {
                return ResourceManager.GetString("We send a one-time code to your inbox every time you sign in. Even if someone lea" +
                        "rns your password, they can\'t reach your work without it.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back, smith..
        /// </summary>
        public static string Welcome_back__smith_ {
            get {
                return ResourceManager.GetString("Welcome back, smith.", resourceCulture);
            }
        }
    }
}
