<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToDoTimeManager.Shared\ToDoTimeManager.Shared.csproj" />
    <ProjectReference Include="..\ToDoTimeManager.WebUI.Utils\ToDoTimeManager.WebUI.Utils.csproj" />
    <ProjectReference Include="..\ToDoTimeManager.WebUI.Models\ToDoTimeManager.WebUI.Models.csproj" />
  </ItemGroup>

</Project>
