CREATE TABLE [dbo].[ToDos]
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Title NVARCHAR(100) NULL,
    Description NVARCHAR(MAX) NULL,
    CreatedAt DATETIME NOT NULL,
    DueDate DATETIME NULL,
    Status INT NOT NULL,
    AssignedTo UNIQUEIDENTIFIER NULL, 
    CONSTRAINT [FK_ToDos_Users] FOREIGN KEY ([AssignedTo]) REFERENCES [Users]([Id])
)
