//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoTimeManager.WebUI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDoTimeManager.WebUI.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All time.
        /// </summary>
        public static string AllTime {
            get {
                return ResourceManager.GetString("AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string CancelledStatus {
            get {
                return ResourceManager.GetString("CancelledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string CompletedStatus {
            get {
                return ResourceManager.GetString("CompletedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string ConfirmLogOut {
            get {
                return ResourceManager.GetString("ConfirmLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new task.
        /// </summary>
        public static string CreateNewTask {
            get {
                return ResourceManager.GetString("CreateNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day ago.
        /// </summary>
        public static string DayAgo {
            get {
                return ResourceManager.GetString("DayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete time log.
        /// </summary>
        public static string DeleteTimeLog {
            get {
                return ResourceManager.GetString("DeleteTimeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete time log?.
        /// </summary>
        public static string DeleteTimeLogConfirm {
            get {
                return ResourceManager.GetString("DeleteTimeLogConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit task.
        /// </summary>
        public static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email/Username.
        /// </summary>
        public static string Email_Username {
            get {
                return ResourceManager.GetString("Email/Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter....
        /// </summary>
        public static string Enter___ {
            get {
                return ResourceManager.GetString("Enter...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter....
        /// </summary>
        public static string Filter___ {
            get {
                return ResourceManager.GetString("Filter...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to registration.
        /// </summary>
        public static string GoToRegistration {
            get {
                return ResourceManager.GetString("GoToRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to sign in.
        /// </summary>
        public static string GoToSignIn {
            get {
                return ResourceManager.GetString("GoToSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours spent.
        /// </summary>
        public static string HoursSpent {
            get {
                return ResourceManager.GetString("HoursSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string InProgressStatus {
            get {
                return ResourceManager.GetString("InProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log date.
        /// </summary>
        public static string LogDate {
            get {
                return ResourceManager.GetString("LogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log description.
        /// </summary>
        public static string LogDescription {
            get {
                return ResourceManager.GetString("LogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log time.
        /// </summary>
        public static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month ago.
        /// </summary>
        public static string MonthAgo {
            get {
                return ResourceManager.GetString("MonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewStatus {
            get {
                return ResourceManager.GetString("NewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks found.
        /// </summary>
        public static string NoTasksFound {
            get {
                return ResourceManager.GetString("NoTasksFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No time logs found.
        /// </summary>
        public static string NoTimeLogsFound {
            get {
                return ResourceManager.GetString("NoTimeLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On hold.
        /// </summary>
        public static string OnHold {
            get {
                return ResourceManager.GetString("OnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On hold.
        /// </summary>
        public static string OnHoldStatus {
            get {
                return ResourceManager.GetString("OnHoldStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don`t match.
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all credentials.
        /// </summary>
        public static string PleaseEnterAllCredentials {
            get {
                return ResourceManager.GetString("PleaseEnterAllCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter сredentials.
        /// </summary>
        public static string PleaseEnterCredentials {
            get {
                return ResourceManager.GetString("PleaseEnterCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent time.
        /// </summary>
        public static string SpentTime {
            get {
                return ResourceManager.GetString("SpentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task create.
        /// </summary>
        public static string TaskCreate {
            get {
                return ResourceManager.GetString("TaskCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task created.
        /// </summary>
        public static string TaskCreated {
            get {
                return ResourceManager.GetString("TaskCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task description.
        /// </summary>
        public static string TaskDescription {
            get {
                return ResourceManager.GetString("TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task details.
        /// </summary>
        public static string TaskDetails {
            get {
                return ResourceManager.GetString("TaskDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task editing.
        /// </summary>
        public static string TaskEdit {
            get {
                return ResourceManager.GetString("TaskEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task number.
        /// </summary>
        public static string TasksNumber {
            get {
                return ResourceManager.GetString("TasksNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task title.
        /// </summary>
        public static string TaskTitle {
            get {
                return ResourceManager.GetString("TaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task with that number were not found.
        /// </summary>
        public static string TaskWithThatNumberWereNotFound {
            get {
                return ResourceManager.GetString("TaskWithThatNumberWereNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time log.
        /// </summary>
        public static string TimeLog {
            get {
                return ResourceManager.GetString("TimeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time loged.
        /// </summary>
        public static string TimeLogCreated {
            get {
                return ResourceManager.GetString("TimeLogCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time log deleted.
        /// </summary>
        public static string TimeLogDeleted {
            get {
                return ResourceManager.GetString("TimeLogDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time log edit.
        /// </summary>
        public static string TimeLogEdit {
            get {
                return ResourceManager.GetString("TimeLogEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time logged.
        /// </summary>
        public static string TimeLogged {
            get {
                return ResourceManager.GetString("TimeLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time logs.
        /// </summary>
        public static string TimeLogs {
            get {
                return ResourceManager.GetString("TimeLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time logs by dates in this month.
        /// </summary>
        public static string TimeLogsByDataes {
            get {
                return ResourceManager.GetString("TimeLogsByDataes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time log updated.
        /// </summary>
        public static string TimeLogUpdated {
            get {
                return ResourceManager.GetString("TimeLogUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User editing.
        /// </summary>
        public static string UserEdit {
            get {
                return ResourceManager.GetString("UserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated.
        /// </summary>
        public static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week ago.
        /// </summary>
        public static string WeekAgo {
            get {
                return ResourceManager.GetString("WeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year ago.
        /// </summary>
        public static string YearAgo {
            get {
                return ResourceManager.GetString("YearAgo", resourceCulture);
            }
        }
    }
}
